name: Build and Push Dockerhub
on:
  push:
    branches: [master]
    paths-ignore:
      - .github/**
      - README.md
  release:
    types: [published]
  schedule:
   - cron:  '0 0 * * *'
jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Docker meta
        id: docker_meta
        uses: docker/metadata-action@v5
        with:
          images: andy008/air-connect
          tags: |
             type=schedule,pattern={{date 'YYYYMMDD'}}
             type=raw,value=latest,enable=${{ github.ref == format('refs/heads/{0}', 'master') }}
             type=semver,pattern={{version}}
      - name: Set up QEMU
        id: qemu
        uses: docker/setup-qemu-action@v3
        with:
          image: tonistiigi/binfmt:latest
          platforms: all
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3
      - name: Dockerhub login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Build and Push
        uses: docker/build-push-action@v5
        id: docker_build
        with:
          context: .
          platforms: linux/arm64/v8,linux/amd64
          push: true
          tags: ${{ steps.docker_meta.outputs.tags }}
      - name: Image digest
        run: "echo Image Digest: ${{ steps.docker_build.outputs.digest }}"
      - name: Image Tag
        run: "echo 'Image Tags: ${{ steps.docker_meta.outputs.tags }}'"